#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0

bspc config window_gap					 12

bspc config single_monocle true
bspc config left_monocle_padding 360
bspc config right_monocle_padding 360
bspc config top_monocle_padding 180
bspc config bottom_monocle_padding 180

bspc config ignore_ewmh_focus true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"

bspc desktop='^2' --layout tiled

bspc rule -a firefox desktop='^2' follow=off focus=off
bspc rule -a KotatogramDesktop desktop='^3' follow=off focus=off
bspc rule -a discord desktop='^3' follow=off focus=off
bspc rule -a Lf desktop='^4' follow=off focus=off
bspc rule -a Lutris desktop='^5' follow=off focus=off
bspc rule -a spotify desktop='^6' follow=off focus=off
bspc rule -a mpv state=floating
bspc rule -a Wpg state=floating
bspc rule -a origin.exe state=floating follow=off focus=off

killall polybar; polybar wpgtk &
killall picom; exec picom &

bash $HOME/.config/bspwm/bspwm_colors.sh &
bash $HOME/.config/wpg/wp_init.sh &
bash $HOME/.config/bspwm/bspwm_colors.sh &

bash $HOME/Scripts/autostart.sh &
