#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"

bspc rule -a TelegramDesktop desktop='^3' follow=off focus=off
bspc rule -a discord desktop='^3' follow=off focus=off
bspc rule -a firefox desktop='^2' follow=off focus=off
bspc rule -a Lutris desktop='^5' follow=off focus=off
bspc rule -a spotify desktop='^6' follow=off focus=off
bspc rule -a mpv state=floating
bspc rule -a origin.exe state=floating follow=off focus=off

killall picom; exec picom &
bash /home/posaydone/.config/bspwm/bspwm_colors.sh &
bash /home/posaydone/.config/wpg/wp_init.sh &
bash /home/posaydone/.config/bspwm/bspwm_colors.sh &